name: Variable Levels Demo

on: push

env:
  GLOBAL_VAR: global

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: job-level

    steps:
      - name: Print global & job
        run: echo "$GLOBAL_VAR $JOB_VAR"

      - name: Step variable example
        env:
          STEP_VAR: step-level
        run: echo "$GLOBAL_VAR $JOB_VAR $STEP_VAR"
