name: myfirst workflow 
on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps: 
        - name: check repo 
          uses: actions/checkout@v6 
        - name: Welcome Message and Read file|
          run:
           echo "My First Github Action Job", ls, cat README.md